name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Update to use the latest version of actions/checkout

    - name: Set up Node.js
      uses: actions/setup-node@v3  # Update to use the latest version of actions/setup-node
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Run Jest tests
      run: npm test

    - name: Build project
      run: npm run build
      
    - name: Create artifact
      uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: dist

    - name: Copy artifacts
      run: |
        mkdir -p artifacts
        cp *.js artifacts/
