name: Use API Key in Workflow

on:
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Print API Key Length
        run: echo "API Key length is ${#API_KEY} characters"
        env:
          API_KEY: ${{ secrets.API_KEY }}
